baseURL: 'https://charlotte-le.com/'
languageCode: en-us
title: Charlotte Le
theme: papermod
publishDir: docs

paginate: 5


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        
        menu:
            main:
                - name: Experience
                  url: experience/
                  weight: 5
                - name: Teaching
                  url: teaching/
                  weight: 10
                - name: Research
                  url: research/
                  weight: 15

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Developing machine learning infrastructure at Slack."
    disableThemeToggle: true
    defaultTheme: light
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    # comments: false
    images: ["papermod-cover.png"]
    assets:
      favicon: "/static/favicon.ico"
      favicon16x16: "/static/favicon.ico" 
      favicon32x32: "/static/favicon.ico" 
    socialIcons: # optional
          - name: "email"
            url: "mailto:charlottele@berkeley.edu"
          - name: "linkedin"
            url: "https://www.linkedin.com/in/charlotte-le/"
          - name: "googlescholar"
            url: "https://scholar.google.com/citations?user=3lAva4oAAAAJ&hl=en" 

    schema:
      publisherType: "Person"
      name: "Charlotte Le"
      description: "Developing machine learning infrastructure at Slack."
      alumniOf: 
        - name: "University of California, Berkeley"
          url: "https://www.berkeley.edu/"
      address: "New York, NY"
      affiliation: 
        - name: "Slack"
          url: "https://slack.com"
        - name: "Berkeley Artificial Intelligence Research Lab"
          url: "https://bair.berkeley.edu/"
        - name: "AUTOLab"
          url: "https://autolab.berkeley.edu/"
        - name: "CS 61A"
          url: "https://cs61a.org/"
      email: "charlottele@berkeley.edu"
      jobTitle: "Machine Learning Engineer and Researcher"
      sameAs:
        - "https://www.linkedin.com/in/charlotte-le/"
        - "https://www.facebook.com/charlotteele/"
        - "https://www.instagram.com/_charlottele/"
        - "https://scholar.google.com/citations?user=3lAva4oAAAAJ&hl=en"
        - "https://openreview.net/profile?id=~Charlotte_Le1"
        - "https://www.researchgate.net/profile/Charlotte-Le-3"


    profileMode:
        enabled: true
        title: Charlotte Le
        email: "charlottele [at] berkeley [dot] com"
        subtitle: "Hi! I'm developing machine learning infrastructure at Slack, working out of New York City.
        
        &nbsp;
   

        &nbsp;


        I received my Bachelor's degree in computer science with EECS honors from UC Berkeley,  
        where I also minored in politics, philosophy, and law.
        During my time there, I conducted research with the Berkeley Artificial Intelligence Research (BAIR) lab and taught as a lecturer for CS 61A."
    
        # buttons:
        #     - name: Experience
        #       url: experience/
        #     - name: Teaching
        #       url: teaching/
        #     - name: Research
        #       url: research/
    
        imageUrl: "https://media.licdn.com/dms/image/v2/D5603AQFKcJkJimSVqA/profile-displayphoto-shrink_800_800/B56ZUXrJcMGsAc-/0/1739858946012?e=1753920000&v=beta&t=fLqu3ecJhcMT2gTluy-gTMDEeAIj7MsbDkj3fz25zYE"
        

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
