baseURL: 'http://charlotte-le.com/'
languageCode: en-us
title: Charlotte Le
theme: papermod
publishDir: docs

paginate: 5


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        
        menu:
            main:
                - name: Experience
                  url: experience/
                  weight: 5
                - name: Teaching
                  url: teaching/
                  weight: 10
                - name: Research
                  url: research/
                  weight: 15



outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Charlotte Le"
    disableThemeToggle: true
    defaultTheme: light
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Charlotte Le
        email: "charlotte [dot] le [at] salesforce [dot] com"
        subtitle: "I am developing machine learning infrastructure at Slack. 
        
        &nbsp;
   

        &nbsp;


        I received my Bachelor's degree in computer science with EECS honors from UC Berkeley,  
        where I also minored in politics, philosophy, and law.
        During my time there, I conducted research with the Berkeley Artificial Intelligence Research (BAIR) lab and served as an instructor for CS 61A."
    
        # buttons:
        #     - name: Experience
        #       url: experience/
        #     - name: Teaching
        #       url: teaching/
        #     - name: Research
        #       url: research/
    

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
